//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turktelekom.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampanya
    {
        public int ID { get; set; }
        public string tur { get; set; }
        public string secenek { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
    }
}
